FROM golang:1.16-alpine AS build-stage
# ビルド
ENV APP_ROOT /build
WORKDIR ${APP_ROOT}
COPY . ${APP_ROOT}
RUN go mod download
RUN go build -o dist/mycircle main.go

FROM alpine:3.14.0
ENV GIN_MODE=release
WORKDIR /app
RUN apk update && apk add --no-cache ca-certificates
COPY --from=build-stage /build/dist /app
CMD [ "./mycircle" ]
