name: フロントエンド単体テスト

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'
      - '.github/workflows/unit-test-front.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'front-end/**'
      - '.github/workflows/unit-test-front.yml'

  # 手動での実行を許可
  workflow_dispatch:

jobs:

  unit-test:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - run: ./front-end/execute_test.sh
